import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Commentify",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang='en' suppressHydrationWarning>
        <body className={`${inter.className} antialiased`}>
          <header className='flex justify-between items-center p-4 gap-5 h-16 mx-10'>
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <p className='text-xl font-semibold'>
                Welcome back, {user?.firstName} to Commentify.
              </p>
              <UserButton />
            </SignedIn>
          </header>
          {children} <Toaster /> <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
